version: '3.8'
services:
  db:
    container_name: 'music_postgres'
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
